<!-- 雷达实现 -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="laser_radius" value="0.03" />
  <xacro:property name="laser_len" value="0.04" />
  
  <xacro:property name="laser_joint_x" value="0" />
  <xacro:property name="laser_joint_y" value="0" />
  <xacro:property name="laser_joint_z" value="${car_height / 2 + laser_len / 2}" />

  <link name="laser">
      <visual>
          <geometry>
              <cylinder radius="${laser_radius}" length="${laser_len}"/>
          </geometry>
          <material name="blue">
              <color rgba="0.1 0.1 0.7 1.0"/>
          </material>
      </visual>
  </link>

  <joint name="laser2base_link" type="fixed">
      <parent link="base_link"/>
      <child link="laser"/>
      <origin xyz="${laser_joint_x} ${laser_joint_y} ${laser_joint_z}"/>
  </joint>

  <gazebo reference="laser">
    <sensor type="ray" name="laser">
      <pose>${laser_joint_x} ${laser_joint_y} ${laser_joint_z} 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>5</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1.000000</resolution>
            <min_angle>0.000000</min_angle>
            <max_angle>6.280000</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.120000</min>
          <max>3.5</max>
          <resolution>0.015000</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
    </ray>

      <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <remapping>~/out:=scan</remapping>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frameName>laser</frameName>
      </plugin>

    </sensor>
  </gazebo>

</robot>