<!-- 摄像头实现 -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="camera_len" value="0.01" />
    <xacro:property name="camera_width" value="0.08" />
    <xacro:property name="camera_high" value="0.02" />

    <xacro:property name="camera_joint_x" value="${car_length / 2 - 0.01}" />
    <xacro:property name="camera_joint_y" value="0.0" />
    <xacro:property name="camera_joint_z" value="${camera_high / 2 + car_height / 2}" />

    <link name="camera">
        <visual>
            <geometry>
                <box size="${camera_len} ${camera_width} ${camera_high}"/>
            </geometry>
        </visual>
    </link>

    <joint name="camera2base_link" type="fixed">
        <parent link="base_link"/>
        <child link="camera"/>
        <origin xyz="${camera_joint_x} ${camera_joint_y} ${camera_joint_z}"/>
    </joint>

    <gazebo reference="camera">
      <sensor type="camera" name="camera1">
        <update_rate>30.0</update_rate>
        <camera name="head">
          <horizontal_fov>1.3962634</horizontal_fov>
          <image>
            <width>800</width>
            <height>800</height>
            <format>R8G8B8</format>
          </image>
          <clip>
            <near>0.02</near>
            <far>300</far>
          </clip>
          <noise>
            <type>gaussian</type>
            <!-- Noise is sampled independently per pixel on each frame.
                  That pixel's noise value is added to each of its color
                  channels, which at that point lie in the range [0,1]. -->
            <mean>0.0</mean>
            <stddev>0.007</stddev>
          </noise>
        </camera>
        <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>0.0</updateRate>
          <cameraName>rrbot/camera1</cameraName>
          <imageTopicName>image_raw</imageTopicName>
          <cameraInfoTopicName>camera_info</cameraInfoTopicName>
          <frameName>camera_link</frameName>
          <hackBaseline>0.07</hackBaseline>
          <distortionK1>0.0</distortionK1>
          <distortionK2>0.0</distortionK2>
          <distortionK3>0.0</distortionK3>
          <distortionT1>0.0</distortionT1>
          <distortionT2>0.0</distortionT2>
        </plugin>
      </sensor>
    </gazebo>
    
</robot>